services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cbaur\CmpMediarenderer\:
    resource: '../Classes/*'

  extbaseSettings.CmpMediaRenderer:
    class: 'array'
    factory:
      - '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      - 'getConfiguration'
    arguments:
      $configurationType: 'Settings'
      $extensionName: 'CmpMediaRenderer'
      $pluginName: ''

  Cbaur\CmpMediarenderer\Services\JavaScriptService:
    arguments:
      $settings: '@extbaseSettings.CmpMediaRenderer'