services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cbaur\CmpMediarenderer\:
    resource: '../Classes/*'

  extbaseSettings.CmpMediarenderer:
    class: 'array'
    factory:
      - '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      - 'getConfiguration'
    arguments:
      $configurationType: 'Settings'
      $extensionName: 'CmpMediarenderer'
  Cbaur\CmpMediarenderer\Services\JavaScriptService:
    public: true
    calls:
      - method: 'injectSettings'
        arguments:
          $settings: '@extbaseSettings.CmpMediarenderer'
